version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mern-blog
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 600
