name: CI/CD MERN Blog

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        pnpm-version: [8.x]
        application-name: ['mern-blog']
        deployment-group: ['mern-blog']
    steps:
      - name: Git checkout project
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CodeDeploy Create Deployment
        run: |
          aws deploy create-deployment \
            --application-name ${{ matrix.application-name }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name ${{ matrix.deployment-group }} \
            --description "${{ matrix.application-name }} ${{ github.sha }}" \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
